[package]
name = "pod"
version = "0.1.0"
authors = ["Kyle McCarthy <km@kylemccarthy.io>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
fn-core = { path = "./../fn-core" }
fn-gateway = { path = "./../fn-gateway" }
failure = "0.1.5"
