networking:
  host: 127.0.0.1
  port: 3000

functions:
  - method: GET
    route: /node
    cmd: node
    handler: ./../examples/node/index.js
    runtime: unix_socket

  - method: GET
    route: /go
    handler: ./../examples/golang/go-function
    runtime: unix_socket

  - method: GET
    route: /wasm
    handler: ./../examples/wasm/target/wasm32-unknown-unknown/debug/wasm.wasm
#    handler: functions/wasm/pkg/wasm_bg.wasm
    runtime: wasm