networking:
  host: 127.0.0.1
  port: 3000

functions:
  - method: GET
    route: /node
    cmd: node
    handler: functions/node/index.js
    runtime: unix_socket

  - method: GET
    route: /go
    handler: functions/golang/go-function
    runtime: unix_socket